package builder

import (
	"errors"

	"github.com/beevik/etree"
	"github.com/diegofxm/cofacture/domain"
	"github.com/diegofxm/cofacture/event"
	ubl "github.com/diegofxm/cofacture/xml"
)

// NOTE ON VERIFICATION: unlike the rest of this package, the structure below was assembled
// from the Technical Annex's field tables (section 6.5.4/6.5.5, Resolución 000165/2023) and
// the standard UBL 2.1 ApplicationResponse schema — it has not yet been cross-checked against
// a real, DIAN-accepted event document the way BuildInvoice/BuildSupportDocument/etc. were.
// Treat it as "should be correct per the annex text" rather than "verified", and confirm
// against the certification (habilitación) environment before relying on it in production.

const (
	applicationResponseCustomizationID = "1"
	applicationResponseProfileID       = "DIAN 2.1: ApplicationResponse de Factura Electrónica de Venta"
)

// BuildAcuseRecibo builds the "Acuse de Recibo de la Factura Electrónica de Venta" event
// (ResponseCode "030", section 6.5.5.3) — the acquirer's acknowledgment that it received the
// document. ev.ReceiverPerson is required: DIAN mandates identifying the natural person who
// received it (cac:DocumentResponse/cac:IssuerParty/cac:Person).
func BuildAcuseRecibo(ev domain.Event) (*etree.Document, error) {
	if ev.ReceiverPerson == nil {
		return nil, errors.New("builder: Acuse de Recibo requires ev.ReceiverPerson")
	}
	doc := buildEventSkeleton(ev)
	dr := appendDocumentResponse(doc.Root(), event.ResponseCodeAcuseRecibo, "Acuse de recibo de Factura Electrónica de Venta", "", "", ev.DocumentReference)
	appendEventIssuerParty(dr, *ev.ReceiverPerson)
	return doc, nil
}

// BuildRecibidoBien builds the "Recibo del Bien y/o Prestación del Servicio" event
// (ResponseCode "032", section 6.5.5.5).
func BuildRecibidoBien(ev domain.Event) (*etree.Document, error) {
	doc := buildEventSkeleton(ev)
	appendDocumentResponse(doc.Root(), event.ResponseCodeRecibidoBien, "Recibo del bien y/o prestación del servicio", "", "", ev.DocumentReference)
	return doc, nil
}

// BuildAceptacionExpresa builds the "Aceptación Expresa" event (ResponseCode "033", section
// 6.5.5.6) — the acquirer's explicit acceptance of the document.
func BuildAceptacionExpresa(ev domain.Event) (*etree.Document, error) {
	doc := buildEventSkeleton(ev)
	appendDocumentResponse(doc.Root(), event.ResponseCodeAceptacionExpresa, "Aceptación expresa", "", "", ev.DocumentReference)
	return doc, nil
}

// BuildAceptacionTacita builds the "Aceptación Tácita" event (ResponseCode "034", section
// 6.5.5.7). Unlike every other event, this one is generated by the ISSUER (not the acquirer)
// and sent to DIAN once 3 business days have passed since Recibo del Bien with no explicit
// acceptance or claim — DIAN requires ev.Note to carry a specific sworn-statement template; see
// event.TacitAcceptanceNote to build it correctly instead of writing it by hand.
func BuildAceptacionTacita(ev domain.Event) (*etree.Document, error) {
	doc := buildEventSkeleton(ev)
	appendDocumentResponse(doc.Root(), event.ResponseCodeAceptacionTacita, "Aceptación Tácita", "", "", ev.DocumentReference)
	return doc, nil
}

// BuildReclamo builds the "Reclamo de la Factura Electrónica de Venta" event (ResponseCode
// "031", section 6.5.5.4) — the acquirer's rejection of the document on commercial grounds.
// r.RejectionListID/r.RejectionName carry the rejection reason from DIAN's catalog (section
// 13.3.11); cofacture does not validate them, same boundary as domain.DiscrepancyResponse.
func BuildReclamo(r domain.Reclamo) (*etree.Document, error) {
	doc := buildEventSkeleton(r.Event)
	appendDocumentResponse(doc.Root(), event.ResponseCodeReclamo, "Reclamo de la Factura Electrónica de Venta", r.RejectionListID, r.RejectionName, r.DocumentReference)
	return doc, nil
}

// buildEventSkeleton builds everything every event shares: namespaces, DIAN extensions,
// header fields, and Sender/ReceiverParty. Callers append their own cac:DocumentResponse.
func buildEventSkeleton(ev domain.Event) *etree.Document {
	doc := etree.NewDocument()
	doc.CreateProcInst("xml", `version="1.0" encoding="UTF-8" standalone="no"`)

	root := doc.CreateElement("ApplicationResponse")
	root.CreateAttr("xmlns", ubl.NSApplicationResponse)
	root.CreateAttr("xmlns:cac", ubl.NSCac)
	root.CreateAttr("xmlns:cbc", ubl.NSCbc)
	root.CreateAttr("xmlns:ds", ubl.NSDs)
	root.CreateAttr("xmlns:ext", ubl.NSExt)
	root.CreateAttr("xmlns:sts", ubl.NSSts)
	root.CreateAttr("xmlns:xades", ubl.NSXades)
	root.CreateAttr("xmlns:xades141", ubl.NSXades141)
	root.CreateAttr("xmlns:xsi", ubl.NSXsi)
	root.CreateAttr("xsi:schemaLocation", ubl.SchemaLocationApplicationResponse)

	appendEventUBLExtensions(root, ev)

	root.CreateElement("cbc:UBLVersionID").SetText("UBL 2.1")
	root.CreateElement("cbc:CustomizationID").SetText(applicationResponseCustomizationID)
	root.CreateElement("cbc:ProfileID").SetText(applicationResponseProfileID)
	root.CreateElement("cbc:ProfileExecutionID").SetText(ev.EnvironmentCode)
	root.CreateElement("cbc:ID").SetText(ev.ID)

	uuid := root.CreateElement("cbc:UUID")
	uuid.CreateAttr("schemeID", ev.EnvironmentCode)
	uuid.CreateAttr("schemeName", "CUDE-SHA384")
	uuid.SetText(ev.CUDE)

	root.CreateElement("cbc:IssueDate").SetText(ev.IssueDate)
	root.CreateElement("cbc:IssueTime").SetText(ev.IssueTime)
	if ev.Note != "" {
		root.CreateElement("cbc:Note").SetText(ev.Note)
	}

	appendEventParty(root, "SenderParty", ev.Sender)
	appendEventParty(root, "ReceiverParty", ev.Receiver)

	return doc
}

// appendEventUBLExtensions mirrors appendUBLExtensions in extensions.go — same DIAN extension
// blocks (InvoiceSource, SoftwareProvider, SoftwareSecurityCode, AuthorizationProvider,
// QRCode) — except events have no sts:InvoiceControl (that group only applies to documents
// with their own DIAN numbering resolution: Invoice and Support Document).
func appendEventUBLExtensions(parent *etree.Element, ev domain.Event) {
	extensions := parent.CreateElement("ext:UBLExtensions")

	dianExt := extensions.CreateElement("ext:UBLExtension").
		CreateElement("ext:ExtensionContent").
		CreateElement("sts:DianExtensions")

	source := dianExt.CreateElement("sts:InvoiceSource").CreateElement("cbc:IdentificationCode")
	source.CreateAttr("listAgencyID", "6")
	source.CreateAttr("listAgencyName", "United Nations Economic Commission for Europe")
	source.CreateAttr("listSchemeURI", "urn:oasis:names:specification:ubl:codelist:gc:CountryIdentificationCode-2.1")
	source.SetText("CO")

	swProvider := dianExt.CreateElement("sts:SoftwareProvider")
	providerID := swProvider.CreateElement("sts:ProviderID")
	providerID.CreateAttr("schemeAgencyID", ubl.DianSchemeAgencyID)
	providerID.CreateAttr("schemeAgencyName", ubl.DianSchemeAgencyName)
	if ev.SoftwareProvider.ProviderIdentification.TypeCode == ubl.IdentificationTypeNIT {
		providerID.CreateAttr("schemeID", ev.SoftwareProvider.ProviderIdentification.VerificationCode)
	}
	providerID.CreateAttr("schemeName", ev.SoftwareProvider.ProviderIdentification.TypeCode)
	providerID.SetText(ev.SoftwareProvider.ProviderIdentification.Number)

	softwareID := swProvider.CreateElement("sts:SoftwareID")
	softwareID.CreateAttr("schemeAgencyID", ubl.DianSchemeAgencyID)
	softwareID.CreateAttr("schemeAgencyName", ubl.DianSchemeAgencyName)
	softwareID.SetText(ev.SoftwareProvider.SoftwareID)

	secCode := dianExt.CreateElement("sts:SoftwareSecurityCode")
	secCode.CreateAttr("schemeAgencyID", ubl.DianSchemeAgencyID)
	secCode.CreateAttr("schemeAgencyName", ubl.DianSchemeAgencyName)
	secCode.SetText(ev.SoftwareSecurityCode)

	authProviderID := dianExt.CreateElement("sts:AuthorizationProvider").CreateElement("sts:AuthorizationProviderID")
	authProviderID.CreateAttr("schemeAgencyID", ubl.DianSchemeAgencyID)
	authProviderID.CreateAttr("schemeAgencyName", ubl.DianSchemeAgencyName)
	authProviderID.CreateAttr("schemeID", "4")
	authProviderID.CreateAttr("schemeName", "31")
	authProviderID.SetText(ubl.DianAuthorizationProviderID)

	dianExt.CreateElement("sts:QRCode").SetText(ev.QRURL)

	// Reserved for the XAdES signature (signer.Sign fills it in later).
	extensions.CreateElement("ext:UBLExtension").CreateElement("ext:ExtensionContent")
}

// appendEventParty adds cac:SenderParty or cac:ReceiverParty (section 6.5.4, groups AAF/AAG) —
// a narrower shape than appendAccountingParty: just PartyTaxScheme, no PartyIdentification,
// PhysicalLocation, PartyLegalEntity or Contact.
func appendEventParty(parent *etree.Element, node string, p domain.EventParty) {
	party := parent.CreateElement("cac:" + node)
	taxScheme := party.CreateElement("cac:PartyTaxScheme")
	taxScheme.CreateElement("cbc:RegistrationName").SetText(p.Name)
	companyID := taxScheme.CreateElement("cbc:CompanyID")
	setIdentificationAttrs(companyID, p.Identification)
	companyID.SetText(p.Identification.Number)
	scheme := taxScheme.CreateElement("cac:TaxScheme")
	scheme.CreateElement("cbc:ID").SetText(p.TaxSchemeCode)
	scheme.CreateElement("cbc:Name").SetText(p.TaxSchemeName)
}

// appendDocumentResponse adds cac:DocumentResponse (section 6.5.5, groups AAH01-09): the event
// code/description and the reference to the document it applies to. rejectionListID/
// rejectionName are only non-empty for Reclamo — they become cbc:ResponseCode's @listID/@name
// attributes; every other event omits both. Returns the cac:DocumentResponse element so callers
// that need to append more to it (Acuse de Recibo's IssuerParty) can.
func appendDocumentResponse(parent *etree.Element, responseCode, description, rejectionListID, rejectionName string, ref domain.EventDocumentReference) *etree.Element {
	dr := parent.CreateElement("cac:DocumentResponse")
	resp := dr.CreateElement("cac:Response")
	rc := resp.CreateElement("cbc:ResponseCode")
	if rejectionListID != "" {
		rc.CreateAttr("listID", rejectionListID)
	}
	if rejectionName != "" {
		rc.CreateAttr("name", rejectionName)
	}
	rc.SetText(responseCode)
	resp.CreateElement("cbc:Description").SetText(description)

	docRef := dr.CreateElement("cac:DocumentReference")
	docRef.CreateElement("cbc:ID").SetText(ref.Prefix + ref.Number)
	uuid := docRef.CreateElement("cbc:UUID")
	uuid.CreateAttr("schemeName", ref.HashType)
	uuid.SetText(ref.CUFE)
	docRef.CreateElement("cbc:DocumentTypeCode").SetText(ref.DocumentTypeCode)

	return dr
}

// appendEventIssuerParty adds cac:DocumentResponse/cac:IssuerParty/cac:Person (section 6.5.5.3,
// groups AAH11-18) — identifies the natural person who received the goods/service, required
// only for Acuse de Recibo.
func appendEventIssuerParty(dr *etree.Element, p domain.EventReceiverPerson) {
	person := dr.CreateElement("cac:IssuerParty").CreateElement("cac:Person")
	id := person.CreateElement("cbc:ID")
	setIdentificationAttrs(id, p.Identification)
	id.SetText(p.Identification.Number)
	person.CreateElement("cbc:FirstName").SetText(p.FirstName)
	person.CreateElement("cbc:FamilyName").SetText(p.FamilyName)
	if p.JobTitle != "" {
		person.CreateElement("cbc:JobTitle").SetText(p.JobTitle)
	}
	if p.OrganizationDepartment != "" {
		person.CreateElement("cbc:OrganizationDepartment").SetText(p.OrganizationDepartment)
	}
}
