package integrationtest

import (
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/diegofxm/cofacture/builder"
	"github.com/diegofxm/cofacture/domain"
	"github.com/diegofxm/cofacture/event"
	"github.com/diegofxm/cofacture/qr"
	"github.com/diegofxm/cofacture/securitycode"
	"github.com/diegofxm/cofacture/signer"
)

// addBusinessDays adds n business days (Mon-Fri) to t, skipping weekends -- a simplification of
// DIAN's "días hábiles" (it does not account for Colombian public holidays, which would require
// a holiday calendar this package doesn't have).
func addBusinessDays(t time.Time, n int) time.Time {
	for n > 0 {
		t = t.AddDate(0, 0, 1)
		if t.Weekday() != time.Saturday && t.Weekday() != time.Sunday {
			n--
		}
	}
	return t
}

// TestBuildAceptacionTacita_LocalOnly builds, computes the CUDE for, and signs a real
// Aceptación Tácita event (ResponseCode "034") referencing an invoice DIAN actually accepted
// today (SETP990078144, sent and validated by TestSendBillSync_Real in this same run) -- but it
// does NOT submit anything to DIAN.
//
// Aceptación Tácita is a sworn statement ("manifiesto bajo la gravedad de juramento...") that 3
// business days passed since a prior Recibido Bien event with no response from the acquirer.
// The referenced invoice here is only minutes old and no Recibido Bien event was ever registered
// for it, so submitting this for real would assert something false into a government system --
// even in the habilitación (test) environment, that's not something to do just to exercise the
// code. This test only verifies the builder/CUDE/signing pipeline locally: the event's own
// IssueDate and the Recibido Bien reference are clearly simulated placeholders, not real DIAN
// records. See docs/apidian-architecture.md / the discussion in this session for the reasoning.
//
// Once a real invoice exists that has genuinely gone 3 business days without a response, this
// same shape (with real dates and a real Recibido Bien reference) is what an actual submission
// via soap.SendEventUpdateStatus should look like.
func TestBuildAceptacionTacita_LocalOnly(t *testing.T) {
	dir := os.Getenv("COFACTURE_TEST_FIXTURES_DIR")
	if dir == "" {
		t.Skip("COFACTURE_TEST_FIXTURES_DIR not set, skipping")
	}

	certPEM, err := os.ReadFile(filepath.Join(dir, "certificado_cert.pem"))
	if err != nil {
		t.Fatalf("read certificate: %v", err)
	}
	keyPEM, err := os.ReadFile(filepath.Join(dir, "certificado_key.pem"))
	if err != nil {
		t.Fatalf("read private key: %v", err)
	}
	cert, key, err := signer.LoadPEM(certPEM, keyPEM)
	if err != nil {
		t.Fatalf("LoadPEM: %v", err)
	}

	env := parseEnvFile(t, filepath.Join(dir, "credenciales.txt"))

	// Real invoice, accepted by DIAN today via TestSendBillSync_Real (see that test's log for the
	// original run: "SETP990078144", StatusCode=00, "ha sido autorizada").
	const (
		invoicePrefix   = "SETP"
		invoiceNumber   = "990078144"
		invoiceCUFE     = "db07502cd11c006f4666e2e299fd77e5a47bd790d9da18786dace4b4d0c4b8972643843e8b7444fe23a0fc8aa1fdf5f2"
		invoiceTypeCode = "01"
	)
	// The invoice was issued "now" in today's run; only the day matters for this simulation.
	invoiceIssueDate := time.Now().In(domain.Bogota)
	// SIMULATED: no real Recibido Bien event exists for this invoice. This is a fabricated
	// reference purely to exercise event.TacitAcceptanceNote's template.
	simulatedEventDate := addBusinessDays(invoiceIssueDate, 3)
	const (
		simulatedRecibidoBienID   = "SIMULATED-1"
		simulatedRecibidoBienCUDE = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
	)

	acquirerName := "Consumidor Final" // the invoice's real customer
	acquirerNIT := "222222222222"

	// Aceptación Tácita is generated by the ISSUER, addressed to DIAN itself (domain.Event's own
	// doc comment: roles are inverted for this one event type).
	ev := domain.Event{
		EnvironmentCode: env["DIAN_ENVIRONMENT"],
		ID:              "1", // event's own sequence -- arbitrary, matches the annex's worked example.
		IssueDate:       simulatedEventDate.Format("2006-01-02"),
		IssueTime:       simulatedEventDate.Format("15:04:05-07:00"),
		Note:            event.TacitAcceptanceNote(simulatedRecibidoBienID, simulatedRecibidoBienCUDE, acquirerName, acquirerNIT),

		DocumentReference: domain.EventDocumentReference{
			Prefix:           invoicePrefix,
			Number:           invoiceNumber,
			CUFE:             invoiceCUFE,
			HashType:         "CUFE-SHA384",
			DocumentTypeCode: invoiceTypeCode,
		},

		Sender: domain.EventParty{
			Name:           "DIEGO FERNANDO MONTOYA VALLEJO",
			Identification: domain.Identification{Number: "6382356", TypeCode: "31", VerificationCode: "7"},
			TaxSchemeCode:  "ZZ",
			TaxSchemeName:  "No aplica",
		},
		Receiver: domain.EventParty{
			Name:           "Unidad Especial Dirección de Impuestos y Aduanas Nacionales",
			Identification: domain.Identification{Number: "800197268", TypeCode: "31", VerificationCode: "4"},
			TaxSchemeCode:  "01",
			TaxSchemeName:  "IVA",
		},

		SoftwareProvider: domain.SoftwareProvider{
			ProviderIdentification: domain.Identification{Number: "6382356", TypeCode: "31", VerificationCode: "7"},
			SoftwareID:             env["DIAN_SOFTWARE_ID"],
		},
	}

	ev.CUDE = event.Compute(
		ev.ID, ev.IssueDate, ev.IssueTime,
		ev.Sender.Identification.Number, ev.Receiver.Identification.Number,
		event.ResponseCodeAceptacionTacita, ev.DocumentReference.Prefix+ev.DocumentReference.Number,
		ev.DocumentReference.DocumentTypeCode, env["DIAN_PIN"],
	)
	// Third argument follows the same pattern as invoices/notes (softwareID+PIN+document's own
	// number) -- events have no prefix, so just the event's own ID.
	ev.SoftwareSecurityCode = securitycode.Compute(env["DIAN_SOFTWARE_ID"], env["DIAN_PIN"], ev.ID)
	// Per domain.Event.QRURL: built from the REFERENCED document's CUFE, not the event's own CUDE.
	ev.QRURL = qr.URL(ev.EnvironmentCode, ev.DocumentReference.CUFE)

	doc, err := builder.BuildAceptacionTacita(ev)
	if err != nil {
		t.Fatalf("BuildAceptacionTacita: %v", err)
	}

	placeholder, err := builder.SignaturePlaceholder(doc)
	if err != nil {
		t.Fatalf("SignaturePlaceholder: %v", err)
	}
	s := signer.New(cert, key)
	// role="supplier": the issuer signs this in the same capacity it signs its own invoices.
	// Unverified against a real DIAN-accepted event (see builder/event.go's top comment) --
	// best-guess, not confirmed.
	if err := s.Sign(doc.Root(), placeholder, "supplier", time.Now().In(domain.Bogota)); err != nil {
		t.Fatalf("Sign: %v", err)
	}

	xmlBytes, err := doc.WriteToBytes()
	if err != nil {
		t.Fatalf("WriteToBytes: %v", err)
	}

	outputsDir := filepath.Join(dir, "outputs")
	if err := os.MkdirAll(outputsDir, 0o755); err != nil {
		t.Fatalf("create outputs/: %v", err)
	}
	outPath := filepath.Join(outputsDir, "_tacit_acceptance.xml")
	if err := os.WriteFile(outPath, xmlBytes, 0o644); err != nil {
		t.Fatalf("save local copy of the XML: %v", err)
	}

	t.Logf("Event CUDE: %s", ev.CUDE)
	t.Logf("References invoice: %s%s (CUFE %s)", invoicePrefix, invoiceNumber, invoiceCUFE)
	t.Logf("Simulated event date (invoice date + 3 business days): %s", ev.IssueDate)
	t.Logf("Signed XML written to: %s", outPath)
	t.Log("NOT submitted to DIAN -- local build/CUDE/signature verification only, see the test's doc comment for why.")
}
